export const galleryItems = [
  {
    front: "/pictures/transition/couple-1.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> June 16, 2024 –</a><br /><br />Unang bulaklak na natanggap mo sakin…<br />gusto mo ng flowers.<br />May nag f-fund raising na student, pinabili mo ako.</p>,
    flower: { src: "/flowers/floater_12.png", w: "9vw", h: "10.5vw", bottom: "-4vw", right: "10vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] ml-[4vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-2.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> June 19, 2024 –</a><br /><br />Unang date pagkatapos ng klaruhan,<br />unang litanya ng “gusto ko magpaligaw”<br />pero sabi ni Lord, “huwag nang patagalin.”<br />Aba, kahit nagka-LBM ako,<br />hindi nakapigil ang kalaban,<br />kasi mas malakas ang plano Niya.</p>,
    flower: { src: "/flowers/floater_13.png", w: "10vw", h: "8vw", bottom: "-5vw", right: "6vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-3.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> June 19, 2024 –</a><br /><br />Unang litrato natin na super lapit.<br />Sheesh, parang tayo na talaga,<br />it's getting real!<br />Pero sabi mo sa akin mag wait pa ako.</p>,
    flower: { src: "/flowers/floater_14.png", w: "12vw", h: "8vw", bottom: "-3vw", right: "6vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] ml-[4vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-4.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> June 25, 2024 –</a><br /><br />Unang date as “official na nanliligaw.”<br />Nag-pray ako, “Bless our fellowship, Lord.”<br />natawa ka pa kasi dapat “date” daw.<br />Eh, saan ba tayo nagsimula? Fellowship din diba?</p>,
    flower: { src: "/flowers/floater_15.png", w: "6vw", h: "8vw", bottom: "-3vw", left: "2vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-6.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> June 28, 2024 –</a><br /><br />Victory@40. Una kong conference,<br />pero mas victory nung binulong mo ang “Yes.”<br />Doon ko unang nahawakan kamay mo…<br />at doon din nagsimula ang “tayo.”</p>,
    flower: { src: "/flowers/floater_16.png", w: "12vw", h: "10vw", bottom: "-4vw", left: "15vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] ml-[4vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-8.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> July 01, 2024 –</a><br /><br />Unang date bilang officially na tayo.<br />Pero group date na naman,<br />kasama ang singles at mga full-time.</p>,
    flower: { src: "/flowers/floater_12.png", w: "9vw", h: "10.5vw", bottom: "-4vw", right: "10vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
   {
    front: "/pictures/transition/couple-9.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> July 02, 2024 –</a><br /><br />Hard launch agad!<br />Sabi nga a testimony should be told, there is no lamp under the bed.<br />Hindi pwedeng itago o isecret ang testimony.<br />Sabi ni Lord, let them see His light sa relationshop natin.<br />At doon nagumpisa magliwanag ang ikaw at ako</p>,
    flower: { src: "/flowers/floater_13.png", w: "10vw", h: "8vw", bottom: "-5vw", right: "6vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-10.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> July 12, 2024 –</a><br /><br />Abay tayo sa kasal ni Ate Rachel,<br />parang prenup lang eh.<br />At ako, tuwang-tuwa,<br />kasi ang ganda ng love ko.</p>,
    flower: { src: "/flowers/floater_14.png", w: "12vw", h: "8vw", bottom: "-3vw", right: "6vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] ml-[4vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-11.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> July 20, 2024 –</a><br /><br />Unang birthday ko na may tayo.<br />Simple lang — pictures sa Old Moon,<br />tapos sa inyo,<br />pero sobra akong masaya,<br />dahil kasama kita.</p>,
    flower: { src: "/flowers/floater_15.png", w: "6vw", h: "8vw", bottom: "-3vw", left: "2vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-13.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> August 28, 2024 –</a><br /><br />Date sa Greenwich, pagkatapos ng away.<br />Tila buwanang pattern,<br />pero buwanan ding panalo,<br />dahil si Lord laging nasa gitna.</p>,
    flower: { src: "/flowers/floater_16.png", w: "12vw", h: "10vw", bottom: "-4vw", left: "15vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] ml-[4vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-14.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> August 28, 2024 –</a><br /><br />Pagmaya continuation —<br />another battle, another victory,<br />with Him, lagi tayong panalo.</p>,
    flower: { src: "/flowers/floater_12.png", w: "9vw", h: "10.5vw", bottom: "-4vw", right: "10vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
   {
    front: "/pictures/transition/couple-15.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> September 10, 2024 –</a><br /><br />Archery date!<br />Sabi mo magaling ka,<br />pero ako, first timer lang —<br />at mas tumama pa.<br />Princess Merida ka nga,<br />pero walang archery skills.</p>,
    flower: { src: "/flowers/floater_13.png", w: "10vw", h: "8vw", bottom: "-5vw", right: "6vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-16.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> September 20, 2024 –</a><br /><br />Night out with your beshies.<br />May bagong jowa si Camla,<br />at kahit di klaro kung okay tayo o hindi,<br />natapos ang gabi na ayos rin tayo.</p>,
    flower: { src: "/flowers/floater_14.png", w: "12vw", h: "8vw", bottom: "-3vw", right: "6vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] ml-[4vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-17.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> September 28, 2024 –</a><br /><br />Random grocery date after school.<br />Minsan ang simpleng lakad,<br />nagiging espesyal pag kasama ka.</p>,
    flower: { src: "/flowers/floater_15.png", w: "6vw", h: "8vw", bottom: "-3vw", left: "2vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-18.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> October 01, 2024 –</a><br /><br />First date of the month sa Checkpoint.<br />Parang milestone din ng love story natin.</p>,
    flower: { src: "/flowers/floater_16.png", w: "12vw", h: "10vw", bottom: "-4vw", left: "15vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] ml-[4vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-19.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> October 20, 2024 –</a><br /><br />Random pictorial after service.<br />Magkakulay ang suot natin,<br />pero ako ang nauna —<br />si Ayra lang naman ang nangopya.</p>,
    flower: { src: "/flowers/floater_12.png", w: "9vw", h: "10.5vw", bottom: "-4vw", right: "10vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
   {
    front: "/pictures/transition/couple-20.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> October 25, 2024 –</a><br /><br />Singles Go Away! Autumn ang theme.<br />Mainit man,<br />pero ang tingin ko sayo malamig at presko,<br />dahil sa ganda ng ngiti mo.</p>,
    flower: { src: "/flowers/floater_13.png", w: "10vw", h: "8vw", bottom: "-5vw", right: "6vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-21.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> November 14, 2024 –</a><br /><br />Purple Book class,<br />nag-volunteer ako,<br />pero kahit volunteerism,<br />hindi kayang pigilan ang “date” natin.</p>,
    flower: { src: "/flowers/floater_14.png", w: "12vw", h: "8vw", bottom: "-3vw", right: "6vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] ml-[4vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-22.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> November 23, 2024 –</a><br /><br />Unang Peniel experience!<br /> At hindi ito ang huli, God is good!</p>,
    flower: { src: "/flowers/floater_15.png", w: "6vw", h: "8vw", bottom: "-3vw", left: "2vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-23.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> December 08, 2024 –</a><br /><br />Ice skating together!<br />Unang pagkafall, maliban sa pagkafall kay Ayra</p>,
    flower: { src: "/flowers/floater_16.png", w: "12vw", h: "10vw", bottom: "-4vw", left: "15vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] ml-[4vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-24.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> December 11, 2024 –</a><br /><br />DIY ramen date!<br />Parang nag workout sa anghang,<br />pero worth it ang pawis, dahil share tayo ng word nyan sa isat isa.</p>,
    flower: { src: "/flowers/floater_12.png", w: "9vw", h: "10.5vw", bottom: "-4vw", right: "10vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
   {
    front: "/pictures/transition/couple-25.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> December 12, 2024 –</a><br /><br />Galing tayong Christmas party,<br />panalo pera at prizes…<br />pero dignity ko, talo.</p>,
    flower: { src: "/flowers/floater_13.png", w: "10vw", h: "8vw", bottom: "-5vw", right: "6vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-26.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> December 21, 2024 –</a><br /><br />Malamig sa Cafe Rosa,<br />pero wala ng mas lalamig pa sa nag iisang single namin na kasama.</p>,
    flower: { src: "/flowers/floater_14.png", w: "12vw", h: "8vw", bottom: "-3vw", right: "6vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] ml-[4vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-27.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> December 25, 2024 –</a><br /><br />Christmas service pictorial!<br />Minsan, random ang moment,<br />pero laging memorable.</p>,
    flower: { src: "/flowers/floater_15.png", w: "6vw", h: "8vw", bottom: "-3vw", left: "2vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-29.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> December 31, 2024 –</a><br /><br />Year End Party!<br />Salamat sa effort mo,<br />you made it happen.</p>,
    flower: { src: "/flowers/floater_16.png", w: "12vw", h: "10vw", bottom: "-4vw", left: "15vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] ml-[4vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-30.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> January 03, 2025 –</a><br /><br />First date of the year!<br />Group date na naman,<br />pero parang prenup ang itsura natin.</p>,
    flower: { src: "/flowers/floater_12.png", w: "9vw", h: "10.5vw", bottom: "-4vw", right: "10vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
   {
    front: "/pictures/transition/couple-31.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> January 03, 2025 –</a><br /><br />Lamok bites,<br />pero tiis ganda para lang sa picture.</p>,
    flower: { src: "/flowers/floater_13.png", w: "10vw", h: "8vw", bottom: "-5vw", right: "6vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-32.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> January 20, 2025 –</a><br /><br />Escalator ride, bili ng waffle.<br />Pero ang naalala ko —<br />bangs mo,<br />at kung gaano kita ka-mahal.</p>,
    flower: { src: "/flowers/floater_14.png", w: "12vw", h: "8vw", bottom: "-3vw", right: "6vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] ml-[4vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-33.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> February 12, 2025 –</a><br /><br />Second Peniel.<br />Bagong mga tao, bagong experience,<br />pero nanatiling mabuti ang Diyos satin.</p>,
    flower: { src: "/flowers/floater_15.png", w: "6vw", h: "8vw", bottom: "-3vw", left: "2vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-34.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> February 14, 2025 –</a><br /><br />Valentine’s Day.<br />Unang totoong bulaklak at tsokolate galing sa’kin.<br />May tampuhan man sa viewdeck,<br />hindi nagwagi ang kaaway.</p>,
    flower: { src: "/flowers/floater_16.png", w: "12vw", h: "10vw", bottom: "-4vw", left: "15vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] ml-[4vw] h-[502px]",
  },
  {
    front: "/pictures/transition/couple-35.jpg",
    back: <p className="text-moss p-4"><a className='font-bold'> February 21, 2025 –</a><br /><br />Unang BGC date.<br />Check ng rings sa Ongpin,<br />event sa Phirst,<br />at ikaw — parang diwata sa paningin ko.</p>,
    flower: { src: "/flowers/floater_12.png", w: "9vw", h: "10.5vw", bottom: "-4vw", right: "10vw" },
    imageSize: { width: 400, height: 502 },
    className: "basis-[41%] mt-[10vw] h-[502px]",
  },
  
];
